
services:
  php-app:
    image: lmao1415/sso
    container_name: single-sign-on
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/var/www/single-sign-on/config/config.json
      - ./.env:/var/www/single-sign-on/config/.env

  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: auth
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - /mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mypassword
    ports:
      - "8001:80"

volumes:
  mysql_data:
    driver: local
